-- local theme = require("theme")
-- local colors = theme.base_30
-- --
-- -- local style = "borderless"
-- local hlgroups = {
--
-- 	TelescopePromptPrefix = {
-- 		fg = colors.red,
-- 		bg = colors.black2,
-- 	},
--
-- 	TelescopeNormal = { bg = colors.darker_black },
--
-- 	TelescopePreviewTitle = {
-- 		fg = colors.black,
-- 		bg = colors.green,
-- 	},
--
-- 	TelescopePromptTitle = {
-- 		fg = colors.black,
-- 		bg = colors.red,
-- 	},
--
-- 	TelescopeSelection = { bg = colors.black2, fg = colors.white },
-- 	TelescopeResultsDiffAdd = { fg = colors.green },
-- 	TelescopeResultsDiffChange = { fg = colors.yellow },
-- 	TelescopeResultsDiffDelete = { fg = colors.red },
-- }
--
-- local styles = {
-- 	borderless = {
-- 		TelescopeBorder = { fg = colors.darker_black, bg = colors.darker_black },
-- 		TelescopePromptBorder = { fg = colors.black2, bg = colors.black2 },
-- 		TelescopePromptNormal = { fg = colors.white, bg = colors.black2 },
-- 		TelescopeResultsTitle = { fg = colors.darker_black, bg = colors.darker_black },
-- 		TelescopePromptPrefix = { fg = colors.red, bg = colors.black2 },
-- 	},
--
-- 	bordered = {
-- 		TelescopeBorder = { fg = colors.one_bg3 },
-- 		TelescopePromptBorder = { fg = colors.one_bg3 },
-- 		TelescopeResultsTitle = { fg = colors.black, bg = colors.green },
-- 		TelescopePreviewTitle = { fg = colors.black, bg = colors.blue },
-- 		TelescopePromptPrefix = { fg = colors.red, bg = colors.black },
-- 		TelescopeNormal = { bg = colors.black },
-- 		TelescopePromptNormal = { bg = colors.black },
-- 	},
-- }
--
-- local highlights = {
-- 	CmpItemAbbr = { fg = colors.white },
-- 	CmpItemAbbrMatch = { fg = colors.blue, bold = true },
-- 	CmpDoc = { bg = colors.darker_black },
-- 	CmpDocBorder = { fg = colors.darker_black, bg = colors.darker_black },
-- 	CmpPmenu = { bg = colors.black },
-- 	CmpSel = { link = "PmenuSel", bold = true },
-- }
--
-- for k, v in pairs(highlights) do
-- 	vim.api.nvim_set_hl(0, k, { bg = v.bg, fg = v.bg })
-- end
-- for k, v in pairs(styles["borderless"]) do
-- 	vim.api.nvim_set_hl(0, k, { bg = v.bg, fg = v.bg })
-- end
-- for k, v in pairs(hlgroups) do
-- 	vim.api.nvim_set_hl(0, k, { bg = v.bg, fg = v.bg })
-- end
-- vim.api.nvim_set_hl(0, "MyNormal", { bg = colors.darker_black, fg = "#ffffff" })
